### ISSUE TITLE
How to authenticate?

### ISSUE THREAD

**Issue by deltamualpha** [mostafazh/hubot-google-analytics#2]
Hi, how does this module authenticate to the google API? What env settings do I need to set? Just the ones in https://www.npmjs.com/package/hubot-googleapi?

**Comment by mostafazh** [comment]
Hi,

You'll need to set the environment variables set here (
https://github.com/en30/hubot-googleapi#required-environment-variables)

Let me know if you have any further questions. Would love to help.

**Comment by Godoy** [comment]
I had the same trouble when I started, maybe we can improve the documentation to close this issue
